using UnityEngine;

public class AutoShooter : MonoBehaviour
{
    public GameObject bulletPrefab; // Mermi prefabęnę buraya sürükle
    public Transform firePoint;     // Merminin çękacađę namlu ucu (Boț bir GameObject)
    public float fireRate = 0.2f;   // Saniyede kaç mermi (Daha düțük = Daha hęzlę)

    private float nextFireTime = 0f;

    void Update()
    {
        // Zamanę geldi mi?
        if (Time.time >= nextFireTime)
        {
            Shoot();
            nextFireTime = Time.time + fireRate;
        }
    }

    void Shoot()
    {
        if (firePoint != null && bulletPrefab != null)
        {
            Instantiate(bulletPrefab, firePoint.position, Quaternion.identity);
        }
    }
}