using UnityEngine;

public class Bullet : MonoBehaviour
{
    public float speed = 20f;
    public int damage = 1;

    void Update()
    {
        // Mermi sürekli sađa gider
        transform.Translate(Vector2.right * speed * Time.deltaTime);

        // Ekrandan çýkarsa (Sađ taraftan) yok et
        if (transform.position.x > 20f)
        {
            Destroy(gameObject);
        }
    }

    // Trigger (Tetikleyici) çarpýţma kontrolü
    void OnTriggerEnter2D(Collider2D other)
    {
        // Eđer çarptýđýmýz ţey "Stone" (Taţ) ise
        if (other.CompareTag("Stone"))
        {
            // Taţýn üzerindeki StoneHealth koduna ulaţ
            StoneHealth stone = other.GetComponent<StoneHealth>();

            if (stone != null)
            {
                stone.TakeDamage(damage); // Hasar ver
            }

            // Mermiyi yok et (Görevi bitti)
            Destroy(gameObject);
        }
    }
}